# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BROGANG.BroGangCLI
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: brogang.exe
  PortableCommandAlias: brogang
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://brogangaicli.pages.dev/downloads/brogang-windows-amd64.zip
  InstallerSha256: 8E028BCCF854A51137A4DEF5C1E8BEBF20527BA8ECF72D2E51516ADD9AF96BED
- Architecture: arm64
  InstallerUrl: https://brogangaicli.pages.dev/downloads/brogang-windows-arm64.zip
  InstallerSha256: 073551C8684BCBF242114360CB490639780FE227DB3328C410000FC2FA9DCE4F
ManifestType: installer
ManifestVersion: 1.12.0
